### PR TITLE
feat: add progress status for moving torrents

### PR DESCRIPTION
**Pull request by aidanaden**

### CODE REVIEW

**Comment by micielski** [comment]
Wait, doesn't transmission return instantaneously for all cases anyway? " Location moved to {display_name}" may be misleading in this case as this may suggest that the operation is done

**Comment by aidanaden** [comment]
> Wait, doesn't transmission return instantaneously for all cases anyway? " Location moved to {display_name}" may be misleading in this case as this may suggest that the operation is done

hmm what would u prefer the message to be then? i think have some form of indication that the "move" command was run successfully is good to have for the user

**Comment by micielski** [comment]
" Moving to {display_name}"?

**Comment by aidanaden** [comment]
> " Moving to {display_name}"?

hmm that's already the message for when the command is pending though ..

**Comment by micielski** [comment]
> hmm that's already the message for when the command is pending though ..

"Request to move sent!" maybe then?

**Comment by aidanaden** [comment]
> "Request to move sent!" maybe then?

hmm that's a different format from our other messages though? adding/deleting torrent messages use the terms "added" and "deleted" so i think maybe it makes sense to use "moved" even though it's not completely accurate?

**Comment by micielski** [comment]
In terms of consistency, yes, but this could be frustrating for the user. The best way to do this would be to really track the location of a torrent, and if it changes, then display the "moved successfully" message. It'd actually put the cool throbber to use

**Comment by aidanaden** [comment]
> In terms of consistency, yes, but this could be frustrating for the user. The best way to do this would be to really track the location of a torrent, and if it changes, then display the "moved successfully" message. It'd actually put the cool throbber to use

this will likely require a much bigger chance since all torrent actions (add, remove, move) will have to be updated to track the actual state of the underlying torrent files, which can be done in another PR

this PR is mainly to provide consistent ui feedback for users, since "move" is the only action with no progress feedback

**Comment by micielski** [comment]
> this will likely require a much bigger chance since all torrent actions (add, remove, move) will have to be updated to track the actual state of the underlying torrent files, which can be done in another PR

I'll be working on making it easier to implement, so don't touch it yet okay, thx

**Pull request merged**
