### PR TITLE
feat: torrent status icons

### PR DESCRIPTION
**Pull request by aidanaden**

### CODE REVIEW

**Review by micielski — CHANGES_REQUESTED** [review]
I think it breaks `auto_hide = true`.
Correct me if I'm wrong

**Comment by aidanaden** [comment]
> I think it breaks `auto_hide = true`. Correct me if I'm wrong

tested it locally but doesnt seem to have any issues? u can test it out just in case because i dont have too many torrents on transmission right now

**Comment by micielski** [comment]
I mean, I have now this one column filled with these ticks:
image
Maybe a better solution would be to add a new column for displaying current status of a torrent which would be at the beginning and one nerd font icon long. For example `nf-fa-pause` when a torrent is paused

**Comment by aidanaden** [comment]
oh sure ya having a status column on the left of the name would be nice:
- downloading would be a "►" icon
- paused would be a pause icon
- completed would be a "✓" icon

looks good?

**Comment by micielski** [comment]
>     * downloading would be a "►" icon

For downloading maybe use the same icon as for download speed

**Comment by aidanaden** [comment]
> For downloading maybe use the same icon as for download speed

it'd feel a bit inconsistent since we're already using pause icon no?

**Comment by micielski** [comment]
> > For downloading maybe use the same icon as for download speed
> 
> it'd feel a bit inconsistent since we're already using pause icon no?

How would you represent seeding then?

**Comment by aidanaden** [comment]
> How would you represent seeding then?

Screenshot 2024-06-24 at 11 44 05 PM

we could use qbittorrent's icons as reference?

**Comment by micielski** [comment]
> we could use qbittorrent's icons as reference?

Sure

**Comment by micielski** [comment]
It still doesn't look good with many torrents:
image
Everything blends in, it's hard to differentiate which torrents are actually being downloaded and which ones are actually uploading something.

**Comment by aidanaden** [comment]
Screenshot 2024-06-25 at 3 02 42 AM

added colors on the status to allow for easier differentation (i don't know what else i can do to make it easier to differentiate between torrents tbh)

should i also set the download icon in the "download speed" column to be green as well ? since it's currently green in the status column

**Pull request closed without merging**
